# Site settings
title: Lucas Moreira - Desenvolvedor Fullstack 
description: Desenvolvedor web 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lucas Moreira 
user_description: Java, JavaScript e Web ❤️ 
email: eskerlucas1@gmail.com 
twitter_username: lucasfauk 
github_username: fauker 
gplus_username:  lorem_ipsum
disqus_username: disqus_GWuARR6lzn 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  #- title: Series
    #url: /series
  #- title: Tags
    #url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
